apiVersion: v2
name: osac-metering
description: OSAC Metering Service — collects metered events from OSAC tenant resource usage
type: application
version: 0.0.6-nightly.20260923.9cc4ee6.106.1
appVersion: "0.0.6-nightly.20260923.9cc4ee6.106.1"
