apiVersion: v2
name: osac-metering
description: OSAC Metering Service — collects metered events from OSAC tenant resource usage
type: application
version: 0.0.4-nightly.20260919.f72117b.99.1
appVersion: "0.0.4-nightly.20260919.f72117b.99.1"
