apiVersion: v2
name: osac-metering
description: OSAC Metering Service — collects metered events from OSAC tenant resource usage
type: application
version: 0.0.3-nightly.20260917.acf5412.94.1
appVersion: "0.0.3-nightly.20260917.acf5412.94.1"
