apiVersion: v2
name: csi-backends
description: Vendor CSI controller deployments for the OSAC CSI meta-driver
type: application
version: 0.0.3-nightly.20260917.1aa5c1e.95.1
appVersion: 0.0.3-nightly.20260917.1aa5c1e.95.1
