apiVersion: v2
name: osac-aap
description: OSAC AAP integration - bootstrap and configuration
type: application
version: 0.0.15-nightly.20260917.acf5412.94.1
appVersion: 0.0.15-nightly.20260917.acf5412.94.1
