apiVersion: v2
name: osac-aap
description: OSAC AAP integration - bootstrap and configuration
type: application
version: 0.0.17-nightly.20260921.07025a6.102.1
appVersion: 0.0.17-nightly.20260921.07025a6.102.1
