apiVersion: v2
name: osac-aap
description: OSAC AAP integration - bootstrap and configuration
type: application
version: 0.0.17-nightly.20260922.c7d420c.103.1
appVersion: 0.0.17-nightly.20260922.c7d420c.103.1
