apiVersion: v2
name: osac-operator
description: OSAC Operator - manages OSAC custom resources
type: application
version: 0.0.17-nightly.20260923.9cc4ee6.106.1
appVersion: 0.0.17-nightly.20260923.9cc4ee6.106.1
