apiVersion: v2
name: osac-operator
description: OSAC Operator - manages OSAC custom resources
type: application
version: 0.0.17-nightly.20260923.0ad47df.105.1
appVersion: 0.0.17-nightly.20260923.0ad47df.105.1
